spring.application.name=deco
# MyBatis \uc124\uc815: mapper \ud3f4\ub354 \uc548\uc758 \ubaa8\ub4e0 xml \ud30c\uc77c\uc744 \uc77d\uc74c
# 1. MyBatis Mapper XML \uc704\uce58 \uc124\uc815 (\ud558\uc704 \ud3f4\ub354 \ud3ec\ud568)
# 'mapper' \ud3f4\ub354 \uc544\ub798\uc758 \ubaa8\ub4e0 \ud3f4\ub354(**)\uc5d0 \uc788\ub294 \ubaa8\ub4e0 xml \ud30c\uc77c\uc744 \uc77d\uc2b5\ub2c8\ub2e4.
mybatis.mapper-locations=classpath:/mapper/**/*.xml

# 2. \uacb0\uacfc \uac12\uc5d0 CamelCase \uc801\uc6a9 (\uc120\ud0dd \uc0ac\ud56d\uc774\uc9c0\ub9cc \uac15\ub825 \ucd94\ucc9c)
# DB\uc758 USER_NAME(snake_case)\uc744 Java\uc758 userName(camelCase)\uc73c\ub85c \uc790\ub3d9\uc73c\ub85c \ub9e4\ud551\ud574\uc90d\ub2c8\ub2e4.
mybatis.configuration.map-underscore-to-camel-case=true

# 3. VO/DTO \ud328\ud0a4\uc9c0 \uacbd\ub85c \uc124\uc815 (\uc120\ud0dd \uc0ac\ud56d)
# XML\uc5d0\uc11c resultType\uc744 \uc4f8 \ub54c \ud328\ud0a4\uc9c0\uba85 \uc0dd\ub7b5\uc744 \uc704\ud574 \uc0ac\uc6a9\ud569\ub2c8\ub2e4. (\uc608: com.example.vo.UserVO -> UserVO)
mybatis.type-aliases-package=com.deco.yanbang.service.vo
# MyBatis \ubcc4\uce6d(Alias) \uc124\uc815
# egovMap\uc774\ub77c\ub294 \uc774\ub984\uc744 \uc4f0\uae30 \uc704\ud574 \uc2e4\uc81c \ud074\ub798\uc2a4 \uacbd\ub85c\ub97c \ub4f1\ub85d\ud569\ub2c8\ub2e4.
mybatis.type-aliases-package=org.egovframe.rte.psl.dataaccess.util
# 1. Database \uc5f0\uacb0 \uc124\uc815 (\ubcf8\uc778\uc758 DB \uc815\ubcf4\ub85c \uc218\uc815)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# localhost:3306/\ub4a4\uc5d0\ub294 \ubcf8\uc778\uc758 DB \uc2a4\ud0a4\ub9c8 \uc774\ub984\uc744 \uc801\uc73c\uc138\uc694.
spring.datasource.url=jdbc:mysql://10.8.0.4:3306/yakbang?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=ruddls030
spring.datasource.password=dlstn0722

jwt:
  # \uc2dc\uc2a4\ud15c \ud658\uacbd\ubcc0\uc218 JWT_SECRET_KEY\ub97c \ucc3e\uace0, \uc5c6\uc73c\uba74 \uc5d0\ub7ec\ub97c \ub0b4\uac70\ub098 \uae30\ubcf8\uac12\uc744 \uc0ac\uc6a9\ud569\ub2c8\ub2e4.
  secret: ${JWT_SECRET_KEY}
